feat: 프론트 도커 추가

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -57,17 +57,38 @@ jobs:
             ${{ runner.os }}-docker-${{ hashFiles('backend/Dockerfile') }}
             ${{ runner.os }}-docker-
 
-      - name: Build Docker image with caching
-        # backend/. 루트 변경 확인 (root에 위치한 Dockerfile 실행 시 변경)
+
+      # 백엔드 이미지 빌드 및 로드
+      - name: Build backend Docker image with caching
         run: |
           docker buildx build \
-            --cache-from=type=local,src=${{ env.CACHE_PATH }}/.buildx-cache \
-            --cache-to=type=local,dest=${{ env.CACHE_PATH }}/.buildx-cache \
-            --tag snapster-app:latest \
-            --file backend/Dockerfile \
-            backend/. \
-            --load \
-            --progress=plain
+          --cache-from=type=local,src=${{ env.CACHE_PATH }}/.buildx-cache \
+          --cache-to=type=local,dest=${{ env.CACHE_PATH }}/.buildx-cache \
+          --tag ${{ env.DOCKER_IMAGE }}-backend:latest \
+          --file backend/Dockerfile \
+          backend/. \
+          --load \
+          --progress=plain
+
+      # 백엔드 이미지 빌드 및 로드
+      - name: Build frontend Docker image
+        run: |
+          docker build \
+          --tag ${{ env.DOCKER_IMAGE }}-frontend:latest \
+          --file frontend/Dockerfile \
+          frontend/.
+
+#      - name: Build Docker image with caching
+#        # backend/. 루트 변경 확인 (root에 위치한 Dockerfile 실행 시 변경)
+#        run: |
+#          docker buildx build \
+#            --cache-from=type=local,src=${{ env.CACHE_PATH }}/.buildx-cache \
+#            --cache-to=type=local,dest=${{ env.CACHE_PATH }}/.buildx-cache \
+#            --tag ${{ env.DOCKER_IMAGE }:latest \
+#            --file backend/Dockerfile \
+#            backend/. \
+#            --load \
+#            --progress=plain
 
       - name: Log into AWS (EC2)
         uses: aws-actions/configure-aws-credentials@v2
@@ -83,70 +104,135 @@ jobs:
           chmod 600 ~/.ssh/id_rsa
           ssh-keyscan ec2-3-34-253-46.ap-northeast-2.compute.amazonaws.com >> ~/.ssh/known_hosts
 
-      - name: Copy Docker image to EC2
+      # 백엔드 도커 이미지 복사
+      - name: Copy backend Docker image to EC2
         run: |
-          docker save snapster-app | gzip > snapster-app.tar.gz
-          scp -i ~/.ssh/id_rsa snapster-app.tar.gz ec2-user@ec2-3-34-253-46.ap-northeast-2.compute.amazonaws.com:/home/ec2-user/snapster/docker
+          docker save ${{ env.DOCKER_IMAGE }}-backend:latest | gzip > backend.tar.gz
+          scp -i ~/.ssh/id_rsa backend.tar.gz ec2-user@ec2-3-34-253-46.ap-northeast-2.compute.amazonaws.com:/home/ec2-user/snapster/docker
+
+      # 프론트 도커 이미지 복사
+      - name: Copy frontend Docker image to EC2
+        run: |
+          docker save ${{ env.DOCKER_IMAGE }}-frontend:latest | gzip > frontend.tar.gz
+          scp -i ~/.ssh/id_rsa frontend.tar.gz ec2-user@ec2-3-34-253-46.ap-northeast-2.compute.amazonaws.com:/home/ec2-user/snapster/docker
+
+      #      - name: Copy Docker image to EC2
+#        run: |
+#          docker save snapster-app | gzip > snapster-app.tar.gz
+#          scp -i ~/.ssh/id_rsa snapster-app.tar.gz ec2-user@ec2-3-34-253-46.ap-northeast-2.compute.amazonaws.com:/home/ec2-user/snapster/docker
 
       - name: SSH into EC2 and Deploy Docker container
         run: |
           REPOSITORY=/home/ec2-user/snapster/docker
-          CONTAINER=${{ env.DOCKER_CONTAINER }}
-          IMAGE=${{ env.DOCKER_IMAGE }}
-          DOCKER_RUN="docker run -d --rm --name $CONTAINER \
-            -p 80:80 \
-            -e KAKAO_CLIENT_SECRET='${{ secrets.KAKAO_CLIENT_SECRET }}' \
-            -e GOOGLE_CLIENT_SECRET='${{ secrets.GOOGLE_CLIENT_SECRET }}' \
-            -e S3_ACCESS_KEY='${{ secrets.S3_ACCESS_KEY }}' \
-            -e S3_SECRET_ACCESS_KEY='${{ secrets.S3_SECRET_ACCESS_KEY }}' \
-            -e JWT_SECRET='${{ secrets.JWT_SECRET }}' \
-            $IMAGE:latest"
+          BACKEND_CONTAINER=${{ env.DOCKER_CONTAINER }}-backend
+          FRONTEND_CONTAINER=${{ env.DOCKER_CONTAINER }}-frontend
+          BACKEND_IMAGE=${{ env.DOCKER_IMAGE }}-backend
+          FRONTEND_IMAGE=${{ env.DOCKER_IMAGE }}-frontend
           
           ssh -i ~/.ssh/id_rsa ec2-user@ec2-3-34-253-46.ap-northeast-2.compute.amazonaws.com <<EOF
+            # 함수 정의: 컨테이너 실행
             run_docker() {
-              local error_message=$1
-              $DOCKER_RUN
-              if [ $? -ne 0 ]; then
-                echo "$error_message"
-                exit 1
+              local name=$1
+              local image=$2
+              local ports=$3
+              local envs=$4
+          
+              # 이미 실행 중인 컨테이너 종료
+              if docker ps | grep -q $name; then
+                docker stop $name
               fi
+              
+              # 기존 이미지 삭제 (존재 시)
+              if docker images | grep -q \$image; then 
+                docker rmi $image || true
+              fi
+          
+              docker container prune -f
+          
+              # 이미지 로드
+              docker load < $REPOSITORY/$image.tar.gz || exit 1
+            
+              # 컨테이너 실행
+              docker run -d --rm --name $name $ports $envs $image:latest
             }
           
-            # 실행 중인 타겟 container 중지 (존재 시)
-            if docker ps | grep -q $CONTAINER; then
-              docker stop $CONTAINER
-            else
-              echo "No running container"
-            fi
+            # 백엔드 실행
+            run_docker "$BACKEND_CONTAINER" "$BACKEND_IMAGE" "-p 80:80" "-e SPRING_PROFILES_ACTIVE=prod \
+              -e KAKAO_CLIENT_SECRET='${{ secrets.KAKAO_CLIENT_SECRET }}' \
+              -e GOOGLE_CLIENT_SECRET='${{ secrets.GOOGLE_CLIENT_SECRET }}' \
+              -e S3_ACCESS_KEY='${{ secrets.S3_ACCESS_KEY }}' \
+              -e S3_SECRET_ACCESS_KEY='${{ secrets.S3_SECRET_ACCESS_KEY }}' \
+              -e JWT_SECRET='${{ secrets.JWT_SECRET }}'"
           
-            # 기존 이미지 삭제 (존재 시)
-            if docker images | grep -q $IMAGE; then
-              docker rmi $IMAGE
-              if [ $? -ne 0 ]; then
-              echo "Failed to remove image"
-              run_docker "Failed to restart previous container"
-              exit 1
-              fi
-            else
-              echo "No existing image"
-            fi
+            # 프론트엔드 실행
+            run_docker "\$FRONTEND_CONTAINER" "\$FRONTEND_IMAGE" "-p 8080:80" ""
           
-            # 실행되지 않는 컨테이너 전부 정리
-            docker container prune -f
+            # 백업 파일 저장
+            cp $REPOSITORY/backend.tar.gz $REPOSITORY/tar_backups/backend.tar.gz
+            cp $REPOSITORY/frontend.tar.gz $REPOSITORY/tar_backups/frontend.tar.gz
           
-            docker load < $REPOSITORY/$IMAGE.tar.gz
-            if [ $? -ne 0 ]; then
-              echo "Failed to load image"
-              run_docker "Failed to restart previous container"
-              exit 1
-            fi
-          
-            # 새로운 컨테이너 실행
-            run_docker "Failed to run container after loading image"
-          
-            cp $REPOSITORY/snapster-app.tar.gz $REPOSITORY/tar_backups/snapster-app.tar.gz
             docker ps
           EOF
+
+#      - name: SSH into EC2 and Deploy Docker container
+#        run: |
+#          REPOSITORY=/home/ec2-user/snapster/docker
+#          CONTAINER=${{ env.DOCKER_CONTAINER }}
+#          IMAGE=${{ env.DOCKER_IMAGE }}
+#          DOCKER_RUN="docker run -d --rm --name $CONTAINER \
+#            -p 80:80 \
+#            -e KAKAO_CLIENT_SECRET='${{ secrets.KAKAO_CLIENT_SECRET }}' \
+#            -e GOOGLE_CLIENT_SECRET='${{ secrets.GOOGLE_CLIENT_SECRET }}' \
+#            -e S3_ACCESS_KEY='${{ secrets.S3_ACCESS_KEY }}' \
+#            -e S3_SECRET_ACCESS_KEY='${{ secrets.S3_SECRET_ACCESS_KEY }}' \
+#            -e JWT_SECRET='${{ secrets.JWT_SECRET }}' \
+#            $IMAGE:latest"
+#
+#          ssh -i ~/.ssh/id_rsa ec2-user@ec2-3-34-253-46.ap-northeast-2.compute.amazonaws.com <<EOF
+#            run_docker() {
+#              local error_message=$1
+#              $DOCKER_RUN
+#              if [ $? -ne 0 ]; then
+#                echo "$error_message"
+#                exit 1
+#              fi
+#            }
+#
+#            # 실행 중인 타겟 container 중지 (존재 시)
+#            if docker ps | grep -q $CONTAINER; then
+#              docker stop $CONTAINER
+#            else
+#              echo "No running container"
+#            fi
+#
+#            # 기존 이미지 삭제 (존재 시)
+#            if docker images | grep -q $IMAGE; then
+#              docker rmi $IMAGE
+#              if [ $? -ne 0 ]; then
+#              echo "Failed to remove image"
+#              run_docker "Failed to restart previous container"
+#              exit 1
+#              fi
+#            else
+#              echo "No existing image"
+#            fi
+#
+#            # 실행되지 않는 컨테이너 전부 정리
+#            docker container prune -f
+#
+#            docker load < $REPOSITORY/$IMAGE.tar.gz
+#            if [ $? -ne 0 ]; then
+#              echo "Failed to load image"
+#              run_docker "Failed to restart previous container"
+#              exit 1
+#            fi
+#
+#            # 새로운 컨테이너 실행
+#            run_docker "Failed to run container after loading image"
+#
+#            cp $REPOSITORY/snapster-app.tar.gz $REPOSITORY/tar_backups/snapster-app.tar.gz
+#            docker ps
+#          EOF
             
 
 
